<?php

namespace AndrewGos\TelegramBot\Tests\DataProvider;

use AndrewGos\TelegramBot\Entity\Message;
use AndrewGos\TelegramBot\Entity\Update;
use AndrewGos\TelegramBot\Entity\UserProfilePhotos;

class ClassBuilderDataDataProvider
{
    public static function generate(): array
    {
        return [
            [
                'class' => Update::class,
                'data' => [
                    'update_id' => 1,
                    'business_connection' => [
                        'id' => 'test_id',
                        'user' => [
                            'id' => 1234,
                            'is_bot' => false,
                            'first_name' => 'Andrey',
                            'last_name' => null,
                            'username' => 'andrey',
                            'language_code' => 'ru',
                        ],
                        'user_chat_id' => 1234,
                        'date' => 1234,
                        'can_reply' => true,
                        'is_enabled' => true,
                    ],
                ],
            ],
            [
                'class' => Message::class,
                'data' => [
                    'message_id' => 1,
                    'message_thread_id' => null,
                    'from' => [
                        'id' => 1234,
                        'is_bot' => false,
                        'first_name' => 'Andrey',
                        'last_name' => null,
                        'username' => 'andrey',
                        'language_code' => 'ru',
                    ],
                    'sender_chat' => null,
                    'sender_boost_count' => null,
                    'date' => 1,
                    'chat' => [
                        'id' => 1234,
                        'first_name' => 'Andrey',
                        'last_name' => null,
                        'username' => 'andrey',
                        'type' => 'private',
                        'is_forum' => false,
                        'title' => null,
                    ],
                    'forward_origin' => [
                        'type' => 'user',
                        'date' => 1234,
                        'sender_user' => [
                            'id' => 1234,
                            'is_bot' => false,
                            'first_name' => 'Andrey',
                            'last_name' => null,
                            'username' => 'andrey',
                            'language_code' => 'ru',
                        ],
                    ],
                    'is_topic_message' => null,
                    'is_automatic_forward' => null,
                    'reply_to_message' => null,
                    'external_reply' => null,
                    'quote' => null,
                    'reply_to_story' => null,
                    'via_bot' => null,
                    'edit_date' => null,
                    'has_protected_content' => null,
                    'media_group_id' => null,
                    'author_signature' => null,
                    'text' => null,
                    'entities' => [],
                    'link_preview_options' => null,
                    'animation' => null,
                    'audio' => null,
                    'document' => null,
                    'photo' => null,
                    'sticker' => null,
                    'story' => null,
                    'video' => null,
                    'video_note' => null,
                    'voice' => null,
                    'caption' => null,
                    'caption_entities' => null,
                    'has_media_spoiler' => null,
                    'contact' => null,
                    'dice' => null,
                    'game' => null,
                    'poll' => null,
                    'venue' => null,
                    'location' => null,
                    'new_chat_members' => null,
                    'left_chat_member' => null,
                    'new_chat_title' => null,
                    'new_chat_photo' => null,
                    'delete_chat_photo' => null,
                    'group_chat_created' => null,
                    'supergroup_chat_created' => null,
                    'channel_chat_created' => null,
                    'message_auto_delete_timer_changed' => null,
                    'migrate_to_chat_id' => null,
                    'migrate_from_chat_id' => null,
                    'pinned_message' => null,
                    'invoice' => null,
                    'successful_payment' => null,
                    'users_shared' => null,
                    'chat_shared' => null,
                    'connected_website' => null,
                    'write_access_allowed' => null,
                    'passport_data' => [
                        'data' => [
                            [
                                'type' => 'personal_details',
                                'data' => 'asdfasdf',
                                'phone_number' => '+79850470321',
                                'email' => null,
                                'files' => [
                                    [
                                        'file_id' => 'asdf',
                                        'file_unique_id' => 'asdf',
                                        'file_size' => 1,
                                        'file_date' => 1,
                                    ],
                                    [
                                        'file_id' => 'asdf',
                                        'file_unique_id' => 'asdf',
                                        'file_size' => 1,
                                        'file_date' => 1,
                                    ],
                                    [
                                        'file_id' => 'asdf',
                                        'file_unique_id' => 'asdf',
                                        'file_size' => 1,
                                        'file_date' => 1,
                                    ],
                                ],
                                'front_side' => null,
                                'reverse_side' => null,
                                'selfie' => null,
                                'translation' => null,
                                'hash' => null,
                            ],
                            [
                                'type' => 'personal_details',
                                'data' => 'asdfasdf',
                                'phone_number' => '+79850470321',
                                'email' => null,
                                'files' => [
                                    [
                                        'file_id' => 'asdf',
                                        'file_unique_id' => 'asdf',
                                        'file_size' => 1,
                                        'file_date' => 1,
                                    ],
                                    [
                                        'file_id' => 'asdf',
                                        'file_unique_id' => 'asdf',
                                        'file_size' => 1,
                                        'file_date' => 1,
                                    ],
                                    [
                                        'file_id' => 'asdf',
                                        'file_unique_id' => 'asdf',
                                        'file_size' => 1,
                                        'file_date' => 2,
                                    ],
                                ],
                                'front_side' => null,
                                'reverse_side' => null,
                                'selfie' => null,
                                'translation' => null,
                                'hash' => null,
                            ],
                        ],
                        'credentials' => [
                            'data' => 'asdf',
                            'hash' => 'asdf',
                            'secret' => 'asdf',
                        ],
                    ],
                    'proximity_alert_triggered' => null,
                    'boost_added' => null,
                    'forum_topic_created' => null,
                    'forum_topic_edited' => null,
                    'forum_topic_closed' => null,
                    'forum_topic_reopened' => null,
                    'general_forum_topic_hidden' => null,
                    'general_forum_topic_unhidden' => null,
                    'giveaway_created' => null,
                    'giveaway' => null,
                    'giveaway_winners' => null,
                    'giveaway_completed' => null,
                    'video_chat_scheduled' => null,
                    'video_chat_started' => null,
                    'video_chat_ended' => null,
                    'video_chat_participants_invited' => null,
                    'web_app_data' => null,
                    'reply_markup' => null,
                    'chat_background_set' => null,
                    'business_connection_id' => null,
                    'sender_business_bot' => null,
                    'is_from_offline' => null,
                    'effect_id' => null,
                    'show_caption_above_media' => null,
                ],
            ],
            [
                'class' => UserProfilePhotos::class,
                'data' => [
                    'total_count' => 1,
                    'photos' => [
                        [
                            [
                                'file_id' => 'asdf',
                                'file_unique_id' => 'asdf',
                                'file_size' => 1,
                                'width' => 1,
                                'height' => 1,
                            ],
                            [
                                'file_id' => 'asdf',
                                'file_unique_id' => 'asdf',
                                'file_size' => 1,
                                'width' => 1,
                                'height' => 1,
                            ],
                        ],
                        [
                            [
                                'file_id' => 'asdf',
                                'file_unique_id' => 'asdf',
                                'file_size' => 1,
                                'width' => 1,
                                'height' => 1,
                            ],
                            [
                                'file_id' => 'asdf',
                                'file_unique_id' => 'asdf',
                                'file_size' => 1,
                                'width' => 1,
                                'height' => 1,
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }
}
