<?php

namespace AndrewGos\TelegramBot\Enum;

enum CountryCodeEnum: string
{
    case AD = 'AD';
    case AE = 'AE';
    case AF = 'AF';
    case AG = 'AG';
    case AI = 'AI';
    case AL = 'AL';
    case AM = 'AM';
    case AO = 'AO';
    case AQ = 'AQ';
    case AR = 'AR';
    case AS = 'AS';
    case AT = 'AT';
    case AU = 'AU';
    case AW = 'AW';
    case AX = 'AX';
    case AZ = 'AZ';
    case BA = 'BA';
    case BB = 'BB';
    case BD = 'BD';
    case BE = 'BE';
    case BF = 'BF';
    case BG = 'BG';
    case BH = 'BH';
    case BI = 'BI';
    case BJ = 'BJ';
    case BL = 'BL';
    case BM = 'BM';
    case BN = 'BN';
    case BO = 'BO';
    case BQ = 'BQ';
    case BR = 'BR';
    case BS = 'BS';
    case BT = 'BT';
    case BV = 'BV';
    case BW = 'BW';
    case BY = 'BY';
    case BZ = 'BZ';
    case CA = 'CA';
    case CC = 'CC';
    case CD = 'CD';
    case CF = 'CF';
    case CG = 'CG';
    case CH = 'CH';
    case CI = 'CI';
    case CK = 'CK';
    case CL = 'CL';
    case CM = 'CM';
    case CN = 'CN';
    case CO = 'CO';
    case CR = 'CR';
    case CU = 'CU';
    case CV = 'CV';
    case CW = 'CW';
    case CX = 'CX';
    case CY = 'CY';
    case CZ = 'CZ';
    case DE = 'DE';
    case DJ = 'DJ';
    case DK = 'DK';
    case DM = 'DM';
    case DO = 'DO';
    case DZ = 'DZ';
    case EC = 'EC';
    case EE = 'EE';
    case EG = 'EG';
    case EH = 'EH';
    case ER = 'ER';
    case ES = 'ES';
    case ET = 'ET';
    case FI = 'FI';
    case FJ = 'FJ';
    case FK = 'FK';
    case FM = 'FM';
    case FO = 'FO';
    case FR = 'FR';
    case GA = 'GA';
    case GB = 'GB';
    case GD = 'GD';
    case GE = 'GE';
    case GF = 'GF';
    case GG = 'GG';
    case GH = 'GH';
    case GI = 'GI';
    case GL = 'GL';
    case GM = 'GM';
    case GN = 'GN';
    case GP = 'GP';
    case GQ = 'GQ';
    case GR = 'GR';
    case GS = 'GS';
    case GT = 'GT';
    case GU = 'GU';
    case GW = 'GW';
    case GY = 'GY';
    case HK = 'HK';
    case HM = 'HM';
    case HN = 'HN';
    case HR = 'HR';
    case HT = 'HT';
    case HU = 'HU';
    case ID = 'ID';
    case IE = 'IE';
    case IL = 'IL';
    case IM = 'IM';
    case IN = 'IN';
    case IO = 'IO';
    case IQ = 'IQ';
    case IR = 'IR';
    case IS = 'IS';
    case IT = 'IT';
    case JE = 'JE';
    case JM = 'JM';
    case JO = 'JO';
    case JP = 'JP';
    case KE = 'KE';
    case KG = 'KG';
    case KH = 'KH';
    case KI = 'KI';
    case KM = 'KM';
    case KN = 'KN';
    case KP = 'KP';
    case KR = 'KR';
    case KW = 'KW';
    case KY = 'KY';
    case KZ = 'KZ';
    case LA = 'LA';
    case LB = 'LB';
    case LC = 'LC';
    case LI = 'LI';
    case LK = 'LK';
    case LR = 'LR';
    case LS = 'LS';
    case LT = 'LT';
    case LU = 'LU';
    case LV = 'LV';
    case LY = 'LY';
    case MA = 'MA';
    case MC = 'MC';
    case MD = 'MD';
    case ME = 'ME';
    case MF = 'MF';
    case MG = 'MG';
    case MH = 'MH';
    case MK = 'MK';
    case ML = 'ML';
    case MM = 'MM';
    case MN = 'MN';
    case MO = 'MO';
    case MP = 'MP';
    case MQ = 'MQ';
    case MR = 'MR';
    case MS = 'MS';
    case MT = 'MT';
    case MU = 'MU';
    case MV = 'MV';
    case MW = 'MW';
    case MX = 'MX';
    case MY = 'MY';
    case MZ = 'MZ';
    case NA = 'NA';
    case NC = 'NC';
    case NE = 'NE';
    case NF = 'NF';
    case NG = 'NG';
    case NI = 'NI';
    case NL = 'NL';
    case NO = 'NO';
    case NP = 'NP';
    case NR = 'NR';
    case NU = 'NU';
    case NZ = 'NZ';
    case OM = 'OM';
    case PA = 'PA';
    case PE = 'PE';
    case PF = 'PF';
    case PG = 'PG';
    case PH = 'PH';
    case PK = 'PK';
    case PL = 'PL';
    case PM = 'PM';
    case PN = 'PN';
    case PR = 'PR';
    case PS = 'PS';
    case PT = 'PT';
    case PW = 'PW';
    case PY = 'PY';
    case QA = 'QA';
    case RE = 'RE';
    case RO = 'RO';
    case RS = 'RS';
    case RU = 'RU';
    case RW = 'RW';
    case SA = 'SA';
    case SB = 'SB';
    case SC = 'SC';
    case SD = 'SD';
    case SE = 'SE';
    case SG = 'SG';
    case SH = 'SH';
    case SI = 'SI';
    case SJ = 'SJ';
    case SK = 'SK';
    case SL = 'SL';
    case SM = 'SM';
    case SN = 'SN';
    case SO = 'SO';
    case SR = 'SR';
    case SS = 'SS';
    case ST = 'ST';
    case SV = 'SV';
    case SX = 'SX';
    case SY = 'SY';
    case SZ = 'SZ';
    case TC = 'TC';
    case TD = 'TD';
    case TF = 'TF';
    case TG = 'TG';
    case TH = 'TH';
    case TJ = 'TJ';
    case TK = 'TK';
    case TL = 'TL';
    case TM = 'TM';
    case TN = 'TN';
    case TO = 'TO';
    case TR = 'TR';
    case TT = 'TT';
    case TV = 'TV';
    case TW = 'TW';
    case TZ = 'TZ';
    case UA = 'UA';
    case UG = 'UG';
    case UM = 'UM';
    case US = 'US';
    case UY = 'UY';
    case UZ = 'UZ';
    case VA = 'VA';
    case VC = 'VC';
    case VE = 'VE';
    case VG = 'VG';
    case VI = 'VI';
    case VN = 'VN';
    case VU = 'VU';
    case WF = 'WF';
    case WS = 'WS';
    case YE = 'YE';
    case YT = 'YT';
    case ZA = 'ZA';
    case ZM = 'ZM';
    case ZW = 'ZW';

    public function getName(): string
    {
        return match ($this) {
            self::AD => "Andorra",
            self::AE => "United Arab Emirates",
            self::AF => "Afghanistan",
            self::AG => "Antigua and Barbuda",
            self::AI => "Anguilla",
            self::AL => "Albania",
            self::AM => "Armenia",
            self::AO => "Angola",
            self::AQ => "Antarctica",
            self::AR => "Argentina",
            self::AS => "American Samoa",
            self::AT => "Austria",
            self::AU => "Australia",
            self::AW => "Aruba",
            self::AX => "Åland Islands",
            self::AZ => "Azerbaijan",
            self::BA => "Bosnia and Herzegovina",
            self::BB => "Barbados",
            self::BD => "Bangladesh",
            self::BE => "Belgium",
            self::BF => "Burkina Faso",
            self::BG => "Bulgaria",
            self::BH => "Bahrain",
            self::BI => "Burundi",
            self::BJ => "Benin",
            self::BL => "Saint Barthélemy",
            self::BM => "Bermuda",
            self::BN => "Brunei Darussalam",
            self::BO => "Bolivia, Plurinational State of",
            self::BQ => "Bonaire, Sint Eustatius and Saba",
            self::BR => "Brazil",
            self::BS => "Bahamas",
            self::BT => "Bhutan",
            self::BV => "Bouvet Island",
            self::BW => "Botswana",
            self::BY => "Belarus",
            self::BZ => "Belize",
            self::CA => "Canada",
            self::CC => "Cocos (Keeling) Islands",
            self::CD => "Congo, Democratic Republic of the",
            self::CF => "Central African Republic",
            self::CG => "Congo",
            self::CH => "Switzerland",
            self::CI => "Côte d'Ivoire",
            self::CK => "Cook Islands",
            self::CL => "Chile",
            self::CM => "Cameroon",
            self::CN => "China",
            self::CO => "Colombia",
            self::CR => "Costa Rica",
            self::CU => "Cuba",
            self::CV => "Cabo Verde",
            self::CW => "Curaçao",
            self::CX => "Christmas Island",
            self::CY => "Cyprus",
            self::CZ => "Czechia",
            self::DE => "Germany",
            self::DJ => "Djibouti",
            self::DK => "Denmark",
            self::DM => "Dominica",
            self::DO => "Dominican Republic",
            self::DZ => "Algeria",
            self::EC => "Ecuador",
            self::EE => "Estonia",
            self::EG => "Egypt",
            self::EH => "Western Sahara",
            self::ER => "Eritrea",
            self::ES => "Spain",
            self::ET => "Ethiopia",
            self::FI => "Finland",
            self::FJ => "Fiji",
            self::FK => "Falkland Islands (Malvinas)",
            self::FM => "Micronesia, Federated States of",
            self::FO => "Faroe Islands",
            self::FR => "France",
            self::GA => "Gabon",
            self::GB => "United Kingdom of Great Britain and Northern Ireland",
            self::GD => "Grenada",
            self::GE => "Georgia",
            self::GF => "French Guiana",
            self::GG => "Guernsey",
            self::GH => "Ghana",
            self::GI => "Gibraltar",
            self::GL => "Greenland",
            self::GM => "Gambia",
            self::GN => "Guinea",
            self::GP => "Guadeloupe",
            self::GQ => "Equatorial Guinea",
            self::GR => "Greece",
            self::GS => "South Georgia and the South Sandwich Islands",
            self::GT => "Guatemala",
            self::GU => "Guam",
            self::GW => "Guinea-Bissau",
            self::GY => "Guyana",
            self::HK => "Hong Kong",
            self::HM => "Heard Island and McDonald Islands",
            self::HN => "Honduras",
            self::HR => "Croatia",
            self::HT => "Haiti",
            self::HU => "Hungary",
            self::ID => "Indonesia",
            self::IE => "Ireland",
            self::IL => "Israel",
            self::IM => "Isle of Man",
            self::IN => "India",
            self::IO => "British Indian Ocean Territory",
            self::IQ => "Iraq",
            self::IR => "Iran, Islamic Republic of",
            self::IS => "Iceland",
            self::IT => "Italy",
            self::JE => "Jersey",
            self::JM => "Jamaica",
            self::JO => "Jordan",
            self::JP => "Japan",
            self::KE => "Kenya",
            self::KG => "Kyrgyzstan",
            self::KH => "Cambodia",
            self::KI => "Kiribati",
            self::KM => "Comoros",
            self::KN => "Saint Kitts and Nevis",
            self::KP => "Korea, Democratic People's Republic of",
            self::KR => "Korea, Republic of",
            self::KW => "Kuwait",
            self::KY => "Cayman Islands",
            self::KZ => "Kazakhstan",
            self::LA => "Lao People's Democratic Republic",
            self::LB => "Lebanon",
            self::LC => "Saint Lucia",
            self::LI => "Liechtenstein",
            self::LK => "Sri Lanka",
            self::LR => "Liberia",
            self::LS => "Lesotho",
            self::LT => "Lithuania",
            self::LU => "Luxembourg",
            self::LV => "Latvia",
            self::LY => "Libya",
            self::MA => "Morocco",
            self::MC => "Monaco",
            self::MD => "Moldova, Republic of",
            self::ME => "Montenegro",
            self::MF => "Saint Martin (French part)",
            self::MG => "Madagascar",
            self::MH => "Marshall Islands",
            self::MK => "North Macedonia",
            self::ML => "Mali",
            self::MM => "Myanmar",
            self::MN => "Mongolia",
            self::MO => "Macao",
            self::MP => "Northern Mariana Islands",
            self::MQ => "Martinique",
            self::MR => "Mauritania",
            self::MS => "Montserrat",
            self::MT => "Malta",
            self::MU => "Mauritius",
            self::MV => "Maldives",
            self::MW => "Malawi",
            self::MX => "Mexico",
            self::MY => "Malaysia",
            self::MZ => "Mozambique",
            self::NA => "Namibia",
            self::NC => "New Caledonia",
            self::NE => "Niger",
            self::NF => "Norfolk Island",
            self::NG => "Nigeria",
            self::NI => "Nicaragua",
            self::NL => "Netherlands, Kingdom of the",
            self::NO => "Norway",
            self::NP => "Nepal",
            self::NR => "Nauru",
            self::NU => "Niue",
            self::NZ => "New Zealand",
            self::OM => "Oman",
            self::PA => "Panama",
            self::PE => "Peru",
            self::PF => "French Polynesia",
            self::PG => "Papua New Guinea",
            self::PH => "Philippines",
            self::PK => "Pakistan",
            self::PL => "Poland",
            self::PM => "Saint Pierre and Miquelon",
            self::PN => "Pitcairn",
            self::PR => "Puerto Rico",
            self::PS => "Palestine, State of",
            self::PT => "Portugal",
            self::PW => "Palau",
            self::PY => "Paraguay",
            self::QA => "Qatar",
            self::RE => "Réunion",
            self::RO => "Romania",
            self::RS => "Serbia",
            self::RU => "Russian Federation",
            self::RW => "Rwanda",
            self::SA => "Saudi Arabia",
            self::SB => "Solomon Islands",
            self::SC => "Seychelles",
            self::SD => "Sudan",
            self::SE => "Sweden",
            self::SG => "Singapore",
            self::SH => "Saint Helena, Ascension and Tristan da Cunha",
            self::SI => "Slovenia",
            self::SJ => "Svalbard and Jan Mayen",
            self::SK => "Slovakia",
            self::SL => "Sierra Leone",
            self::SM => "San Marino",
            self::SN => "Senegal",
            self::SO => "Somalia",
            self::SR => "Suriname",
            self::SS => "South Sudan",
            self::ST => "Sao Tome and Principe",
            self::SV => "El Salvador",
            self::SX => "Sint Maarten (Dutch part)",
            self::SY => "Syrian Arab Republic",
            self::SZ => "Eswatini",
            self::TC => "Turks and Caicos Islands",
            self::TD => "Chad",
            self::TF => "French Southern Territories",
            self::TG => "Togo",
            self::TH => "Thailand",
            self::TJ => "Tajikistan",
            self::TK => "Tokelau",
            self::TL => "Timor-Leste",
            self::TM => "Turkmenistan",
            self::TN => "Tunisia",
            self::TO => "Tonga",
            self::TR => "Türkiye",
            self::TT => "Trinidad and Tobago",
            self::TV => "Tuvalu",
            self::TW => "Taiwan, Province of China[note 1]",
            self::TZ => "Tanzania, United Republic of",
            self::UA => "Ukraine",
            self::UG => "Uganda",
            self::UM => "United States Minor Outlying Islands",
            self::US => "United States of America",
            self::UY => "Uruguay",
            self::UZ => "Uzbekistan",
            self::VA => "Holy See",
            self::VC => "Saint Vincent and the Grenadines",
            self::VE => "Venezuela, Bolivarian Republic of",
            self::VG => "Virgin Islands (British)",
            self::VI => "Virgin Islands (U.S.)",
            self::VN => "Viet Nam",
            self::VU => "Vanuatu",
            self::WF => "Wallis and Futuna",
            self::WS => "Samoa",
            self::YE => "Yemen",
            self::YT => "Mayotte",
            self::ZA => "South Africa",
            self::ZM => "Zambia",
            self::ZW => "Zimbabwe",
            default => $this->value,
        };
    }
}
