<?php

namespace AndrewGos\TelegramBot\Enum;

enum CurrencyEnum: string
{
    case AED = 'AED';
    case AFN = 'AFN';
    case ALL = 'ALL';
    case AMD = 'AMD';
    case ARS = 'ARS';
    case AUD = 'AUD';
    case AZN = 'AZN';
    case BAM = 'BAM';
    case BDT = 'BDT';
    case BGN = 'BGN';
    case BND = 'BND';
    case BOB = 'BOB';
    case BRL = 'BRL';
    case BYN = 'BYN';
    case CAD = 'CAD';
    case CHF = 'CHF';
    case CLP = 'CLP';
    case CNY = 'CNY';
    case COP = 'COP';
    case CRC = 'CRC';
    case CZK = 'CZK';
    case DKK = 'DKK';
    case DOP = 'DOP';
    case DZD = 'DZD';
    case EGP = 'EGP';
    case ETB = 'ETB';
    case EUR = 'EUR';
    case GBP = 'GBP';
    case GEL = 'GEL';
    case GTQ = 'GTQ';
    case HKD = 'HKD';
    case HNL = 'HNL';
    case HRK = 'HRK';
    case HUF = 'HUF';
    case IDR = 'IDR';
    case ILS = 'ILS';
    case INR = 'INR';
    case ISK = 'ISK';
    case JMD = 'JMD';
    case JPY = 'JPY';
    case KES = 'KES';
    case KGS = 'KGS';
    case KRW = 'KRW';
    case KZT = 'KZT';
    case LBP = 'LBP';
    case LKR = 'LKR';
    case MAD = 'MAD';
    case MDL = 'MDL';
    case MNT = 'MNT';
    case MUR = 'MUR';
    case MVR = 'MVR';
    case MXN = 'MXN';
    case MYR = 'MYR';
    case MZN = 'MZN';
    case NGN = 'NGN';
    case NIO = 'NIO';
    case NOK = 'NOK';
    case NPR = 'NPR';
    case NZD = 'NZD';
    case PAB = 'PAB';
    case PEN = 'PEN';
    case PHP = 'PHP';
    case PKR = 'PKR';
    case PLN = 'PLN';
    case PYG = 'PYG';
    case QAR = 'QAR';
    case RON = 'RON';
    case RSD = 'RSD';
    case RUB = 'RUB';
    case SAR = 'SAR';
    case SEK = 'SEK';
    case SGD = 'SGD';
    case THB = 'THB';
    case TJS = 'TJS';
    case TRY = 'TRY';
    case TTD = 'TTD';
    case TWD = 'TWD';
    case TZS = 'TZS';
    case UAH = 'UAH';
    case UGX = 'UGX';
    case USD = 'USD';
    case UYU = 'UYU';
    case UZS = 'UZS';
    case VND = 'VND';
    case YER = 'YER';
    case XTR = 'XTR';
    case ZAR = 'ZAR';

    public function getSymbol(): string
    {
        return match ($this) {
            self::AED => 'د.إ.‏',
            self::AFN => '؋',
            self::ALL => 'Lek',
            self::AMD => 'դր.',
            self::ARS => '$',
            self::AUD => '$',
            self::AZN => 'ман.',
            self::BAM => 'KM',
            self::BDT => '৳',
            self::BGN => 'лв.',
            self::BND => '$',
            self::BOB => 'Bs',
            self::BRL => 'R$',
            self::BYN => 'BYN',
            self::CAD => '$',
            self::CHF => 'CHF',
            self::CLP => '$',
            self::CNY => 'CN¥',
            self::COP => '$',
            self::CRC => '₡',
            self::CZK => 'Kč',
            self::DKK => 'kr',
            self::DOP => '$',
            self::DZD => 'د.ج.‏',
            self::EGP => 'ج.م.‏',
            self::ETB => 'ብር',
            self::EUR => '€',
            self::GBP => '£',
            self::GEL => 'GEL',
            self::GTQ => 'Q',
            self::HKD => '$',
            self::HNL => 'L',
            self::HRK => 'kn',
            self::HUF => 'Ft',
            self::IDR => 'Rp',
            self::ILS => '₪',
            self::INR => '₹',
            self::ISK => 'kr',
            self::JMD => '$',
            self::JPY => '￥',
            self::KES => 'Ksh',
            self::KGS => 'KGS',
            self::KRW => '₩',
            self::KZT => '₸',
            self::LBP => 'ل.ل.‏',
            self::LKR => 'රු.',
            self::MAD => 'د.م.‏',
            self::MDL => 'MDL',
            self::MNT => 'MNT',
            self::MUR => 'MUR',
            self::MVR => 'MVR',
            self::MXN => '$',
            self::MYR => 'RM',
            self::MZN => 'MTn',
            self::NGN => '₦',
            self::NIO => 'C$',
            self::NOK => 'kr',
            self::NPR => 'नेरू',
            self::NZD => '$',
            self::PAB => 'B/.',
            self::PEN => 'S/.',
            self::PHP => '₱',
            self::PKR => '₨',
            self::PLN => 'zł',
            self::PYG => '₲',
            self::QAR => 'ر.ق.‏',
            self::RON => 'RON',
            self::RSD => 'дин.',
            self::RUB => '₽',
            self::SAR => 'ر.س.‏',
            self::SEK => 'kr',
            self::SGD => '$',
            self::THB => '฿',
            self::TJS => 'TJS',
            self::TRY => 'TL',
            self::TTD => '$',
            self::TWD => 'NT$',
            self::TZS => 'TSh',
            self::UAH => '₴',
            self::UGX => 'USh',
            self::USD => '$',
            self::UYU => '$',
            self::UZS => 'UZS',
            self::VND => '₫',
            self::YER => 'ر.ي.‏',
            self::XTR => 'XTR',
            self::ZAR => 'R',
            default => $this->value,
        };
    }

    public function getName(): string
    {
        return match ($this) {
            self::AED => 'United Arab Emirates Dirham',
            self::AFN => 'Afghan Afghani',
            self::ALL => 'Albanian Lek',
            self::AMD => 'Armenian Dram',
            self::ARS => 'Argentine Peso',
            self::AUD => 'Australian Dollar',
            self::AZN => 'Azerbaijani Manat',
            self::BAM => 'Bosnia & Herzegovina Convertible Mark',
            self::BDT => 'Bangladeshi Taka',
            self::BGN => 'Bulgarian Lev',
            self::BND => 'Brunei Dollar',
            self::BOB => 'Bolivian Boliviano',
            self::BRL => 'Brazilian Real',
            self::BYN => 'Belarusian ruble',
            self::CAD => 'Canadian Dollar',
            self::CHF => 'Swiss Franc',
            self::CLP => 'Chilean Peso',
            self::CNY => 'Chinese Renminbi Yuan',
            self::COP => 'Colombian Peso',
            self::CRC => 'Costa Rican Colón',
            self::CZK => 'Czech Koruna',
            self::DKK => 'Danish Krone',
            self::DOP => 'Dominican Peso',
            self::DZD => 'Algerian Dinar',
            self::EGP => 'Egyptian Pound',
            self::ETB => 'Ethiopian Birr',
            self::EUR => 'Euro',
            self::GBP => 'British Pound',
            self::GEL => 'Georgian Lari',
            self::GTQ => 'Guatemalan Quetzal',
            self::HKD => 'Hong Kong Dollar',
            self::HNL => 'Honduran Lempira',
            self::HRK => 'Croatian Kuna',
            self::HUF => 'Hungarian Forint',
            self::IDR => 'Indonesian Rupiah',
            self::ILS => 'Israeli New Sheqel',
            self::INR => 'Indian Rupee',
            self::ISK => 'Icelandic Króna',
            self::JMD => 'Jamaican Dollar',
            self::JPY => 'Japanese Yen',
            self::KES => 'Kenyan Shilling',
            self::KGS => 'Kyrgyzstani Som',
            self::KRW => 'South Korean Won',
            self::KZT => 'Kazakhstani Tenge',
            self::LBP => 'Lebanese Pound',
            self::LKR => 'Sri Lankan Rupee',
            self::MAD => 'Moroccan Dirham',
            self::MDL => 'Moldovan Leu',
            self::MNT => 'Mongolian Tögrög',
            self::MUR => 'Mauritian Rupee',
            self::MVR => 'Maldivian Rufiyaa',
            self::MXN => 'Mexican Peso',
            self::MYR => 'Malaysian Ringgit',
            self::MZN => 'Mozambican Metical',
            self::NGN => 'Nigerian Naira',
            self::NIO => 'Nicaraguan Córdoba',
            self::NOK => 'Norwegian Krone',
            self::NPR => 'Nepalese Rupee',
            self::NZD => 'New Zealand Dollar',
            self::PAB => 'Panamanian Balboa',
            self::PEN => 'Peruvian Nuevo Sol',
            self::PHP => 'Philippine Peso',
            self::PKR => 'Pakistani Rupee',
            self::PLN => 'Polish Złoty',
            self::PYG => 'Paraguayan Guaraní',
            self::QAR => 'Qatari Riyal',
            self::RON => 'Romanian Leu',
            self::RSD => 'Serbian Dinar',
            self::RUB => 'Russian Ruble',
            self::SAR => 'Saudi Riyal',
            self::SEK => 'Swedish Krona',
            self::SGD => 'Singapore Dollar',
            self::THB => 'Thai Baht',
            self::TJS => 'Tajikistani Somoni',
            self::TRY => 'Turkish Lira',
            self::TTD => 'Trinidad and Tobago Dollar',
            self::TWD => 'New Taiwan Dollar',
            self::TZS => 'Tanzanian Shilling',
            self::UAH => 'Ukrainian Hryvnia',
            self::UGX => 'Ugandan Shilling',
            self::USD => 'United States Dollar',
            self::UYU => 'Uruguayan Peso',
            self::UZS => 'Uzbekistani Som',
            self::VND => 'Vietnamese Đồng',
            self::YER => 'Yemeni Rial',
            self::XTR => 'Telegram XTR',
            self::ZAR => 'South African Rand',
            default => $this->value,
        };
    }
}
